[package]
name = "snippset"
version = "0.5.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
copypasta = "0.10.1"
crossterm = "0.27.0"
inquire = "0.7.5"
serde_json = "1.0.117"
