[package]
name = "snippset"
version = "0.5.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.7", features = ["derive"] }
crossterm = "0.27.0"
inquire = "0.7.5"
ratatui = "0.29.0"
serde_json = "1.0.117"

[dev-dependencies]
insta = "1.41.1"
